# Change these first
owner: chimoney # Your GitHub organization or username, where this repository lives
repo: chimoney-status # The name of this repository

sites:
  - name: Chimoney API V2
    url: https://api.chimoney.io
  - name: Chimoney Website
    url: https://chimoney.io
  - name: Chimoney Web Platform
    url: https://dash.chimoney.io
  - name: Chimoney API V1
    url: https://live.chimoney.io
  - name: Unispend
    url: https://unispend.com
  - name: Scrim by Chimoney Website
    url: https://scrim.ai
  - name: Scrim by Chimoney API
    url: https://api.scrim.ai

assignees: # Users to assign downtime issues (optional)
  - uchibeke
  - Regedit-msc
  - adebayoileri
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /chimoney-status
  logoUrl: https://chimoney.io/assets/icons/chimoney-logo.svg
  name: Chimoney Status
  theme: light
  introTitle: "**Chimoney** enables efficient cross-border payouts and disbursements for emerging platforms, financial institutions, and creator communities through it’s APIs and web Platform."
  introMessage: This is the Chimoney status page which uses **real-time** data from our [GitHub repository](https://github.com/Chimoney/chimoney-status).
  navbar:
    - title: Status
      href: /chimoney-status
    - title: chimoney.io
      href: https://chimoney.io/
    - title: API
      href: https://chimoney.readme.io/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
